---
language: python
python: "2.7"

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Java JDK
jdk:
  - oraclejdk8

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Update apt
  - sudo apt-get update -qq

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the playbook with ansible-playbook
  - ansible-playbook tests/test.yml -i tests/inventory

  # Use sudo to get our mvn rather than the TravisCI mvn
  - "readlink -f $(sudo which mvn)"

  # Check Maven is installed
  - 'M2_HOME="$(dirname $(dirname $(readlink -f $(sudo which mvn))))" sudo mvn --version'
  - readlink -f $(sudo which mvnDebug)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
