# code: language=ansible
---
- name: Load version vars
  ansible.builtin.include_vars: "{{ __current_item }}"

  #ansible.builtin.include_vars: '{{ item }}'
  with_items:
    - ../vars/versions/default.yml
    - '../vars/versions/{{ maven_version }}.yml'
  loop_control:
    loop_var: "__current_item"

- name: If checksum setup
  ansible.builtin.assert:
    that:
      - "maven_redis_checksum not in (None, '')"

- name: Install which (yum, dnf, zypper)
  become: true
  ansible.builtin.package:
    name: which
    state: present
  when: ansible_pkg_mgr in ('yum', 'dnf', 'zypper')

- name: Create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ maven_download_dir }}'

- name: Download Maven
  ansible.builtin.get_url:
    url: '{{ maven_mirror }}/{{ maven_redis_filename }}'
    dest: '{{ maven_download_dir }}/{{ maven_redis_filename }}'
    checksum: '{{ maven_algo_checksum }}:{{ maven_redis_checksum }}'
    force: false
    use_proxy: '{{ maven_use_proxy }}'
    validate_certs: '{{ maven_validate_certs }}'
    timeout: '{{ maven_download_timeout }}'
    mode: 'u=rw,go=r'

- name: Create Maven installation directory
  become: true
  ansible.builtin.file:
    state: directory
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'u=rwx,go=rx'
    dest: '{{ maven_install_dir }}'

- name: Install unarchive module dependencies (dnf, zypper)
  become: true
  ansible.builtin.package:
    name:
      - tar
      - unzip
      - gzip
    state: present
  when: ansible_pkg_mgr in ('dnf', 'zypper')

- name: Install Maven
  become: true
  ansible.builtin.unarchive:
    src: '{{ maven_download_dir }}/{{ maven_redis_filename }}'
    dest: '{{ maven_install_dir }}'
    copy: false
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'go-w'
    creates: '{{ maven_install_dir }}/apache-maven-{{ maven_version }}'

- name: Create symbolic links
  ansible.builtin.include_tasks: create-symbolic-links.yml
  when: maven_is_default_installation

- name: Create Ansible facts.d directory
  become: true
  ansible.builtin.file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'u=rwx,go=rx'

- name: Install Maven facts
  become: true
  ansible.builtin.template:
    src: facts.j2
    dest: '/etc/ansible/facts.d/{{ maven_fact_group_name }}.fact'
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'u=rw,go=r'

- name: Re-read facts
  ansible.builtin.setup:
    filter: ansible_local
