---
- name: load version vars
  with_first_found:
    - '../vars/versions/{{ maven_version }}.yml'
    - ../vars/versions/default.yml
  include_vars: '{{ item }}'

- name: assert version vars
  assert:
    that:
      - "maven_redis_sha256sum not in (None, '')"

- name: install which (yum, dnf, zypper)
  become: yes
  package:
    name: which
    state: present
  when: ansible_pkg_mgr in ('yum', 'dnf', 'zypper')

- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ maven_download_dir }}'

- name: download Maven
  get_url:
    url: '{{ maven_mirror }}/{{ maven_redis_filename }}'
    dest: '{{ maven_download_dir }}/{{ maven_redis_filename }}'
    checksum: 'sha256:{{ maven_redis_sha256sum }}'
    force: no
    use_proxy: '{{ maven_use_proxy }}'
    validate_certs: '{{ maven_validate_certs }}'
    timeout: '{{ maven_download_timeout }}'
    mode: 'u=rw,go=r'

- name: create Maven installation directory
  become: yes
  file:
    state: directory
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'u=rwx,go=rx'
    dest: '{{ maven_install_dir }}'

- name: install unarchive module dependencies (dnf, zypper)
  become: yes
  package:
    name:
      - tar
      - unzip
      - gzip
    state: present
  when: ansible_pkg_mgr in ('dnf', 'zypper')

- name: install Maven
  become: yes
  unarchive:
    src: '{{ maven_download_dir }}/{{ maven_redis_filename }}'
    dest: '{{ maven_install_dir }}'
    copy: no
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'go-w'
    creates: '{{ maven_install_dir }}/apache-maven-{{ maven_version }}'

- name: create symbolic links
  include_tasks: create-symbolic-links.yml
  when: maven_is_default_installation

- name: create Ansible facts.d directory
  become: yes
  file:
    state: directory
    dest: /etc/ansible/facts.d
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'u=rwx,go=rx'

- name: install Maven facts
  become: yes
  template:
    src: facts.j2
    dest: '/etc/ansible/facts.d/{{ maven_fact_group_name }}.fact'
    owner: root
    # Use group ID as group name varies by OS (e.g. root/wheel)
    group: '0'
    mode: 'u=rw,go=r'

- name: re-read facts
  setup:
    filter: ansible_local
