---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install jdk 7
      become: yes
      apt:
        name: openjdk-7-jdk
        state: present

  roles:
    - role: ansible-role-maven
      maven_version: '3.6.0'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: verify default maven facts
      assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
